# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/george/Desktop/projects/DP5/code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/george/Desktop/projects/DP5/code

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/george/Desktop/projects/DP5/code/CMakeFiles /home/george/Desktop/projects/DP5/code/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/george/Desktop/projects/DP5/code/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Percy++

# Build rule for target.
Percy++: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Percy++
.PHONY : Percy++

# fast build rule for target.
Percy++/fast:
	$(MAKE) -f CMakeFiles/Percy++.dir/build.make CMakeFiles/Percy++.dir/build
.PHONY : Percy++/fast

#=============================================================================
# Target rules for targets named Relic

# Build rule for target.
Relic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Relic
.PHONY : Relic

# fast build rule for target.
Relic/fast:
	$(MAKE) -f CMakeFiles/Relic.dir/build.make CMakeFiles/Relic.dir/build
.PHONY : Relic/fast

#=============================================================================
# Target rules for targets named bytearray_unittest

# Build rule for target.
bytearray_unittest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bytearray_unittest
.PHONY : bytearray_unittest

# fast build rule for target.
bytearray_unittest/fast:
	$(MAKE) -f CMakeFiles/bytearray_unittest.dir/build.make CMakeFiles/bytearray_unittest.dir/build
.PHONY : bytearray_unittest/fast

#=============================================================================
# Target rules for targets named curve25519-donna

# Build rule for target.
curve25519-donna: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 curve25519-donna
.PHONY : curve25519-donna

# fast build rule for target.
curve25519-donna/fast:
	$(MAKE) -f CMakeFiles/curve25519-donna.dir/build.make CMakeFiles/curve25519-donna.dir/build
.PHONY : curve25519-donna/fast

#=============================================================================
# Target rules for targets named dp5

# Build rule for target.
dp5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dp5
.PHONY : dp5

# fast build rule for target.
dp5/fast:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/build
.PHONY : dp5/fast

#=============================================================================
# Target rules for targets named dp5clib

# Build rule for target.
dp5clib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dp5clib
.PHONY : dp5clib

# fast build rule for target.
dp5clib/fast:
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/build
.PHONY : dp5clib/fast

#=============================================================================
# Target rules for targets named dp5combregclient_unittest

# Build rule for target.
dp5combregclient_unittest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dp5combregclient_unittest
.PHONY : dp5combregclient_unittest

# fast build rule for target.
dp5combregclient_unittest/fast:
	$(MAKE) -f CMakeFiles/dp5combregclient_unittest.dir/build.make CMakeFiles/dp5combregclient_unittest.dir/build
.PHONY : dp5combregclient_unittest/fast

#=============================================================================
# Target rules for targets named dp5lookupclient_unittest

# Build rule for target.
dp5lookupclient_unittest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dp5lookupclient_unittest
.PHONY : dp5lookupclient_unittest

# fast build rule for target.
dp5lookupclient_unittest/fast:
	$(MAKE) -f CMakeFiles/dp5lookupclient_unittest.dir/build.make CMakeFiles/dp5lookupclient_unittest.dir/build
.PHONY : dp5lookupclient_unittest/fast

#=============================================================================
# Target rules for targets named dp5metadata_unittest

# Build rule for target.
dp5metadata_unittest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dp5metadata_unittest
.PHONY : dp5metadata_unittest

# fast build rule for target.
dp5metadata_unittest/fast:
	$(MAKE) -f CMakeFiles/dp5metadata_unittest.dir/build.make CMakeFiles/dp5metadata_unittest.dir/build
.PHONY : dp5metadata_unittest/fast

#=============================================================================
# Target rules for targets named enc_test

# Build rule for target.
enc_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enc_test
.PHONY : enc_test

# fast build rule for target.
enc_test/fast:
	$(MAKE) -f CMakeFiles/enc_test.dir/build.make CMakeFiles/enc_test.dir/build
.PHONY : enc_test/fast

#=============================================================================
# Target rules for targets named googletest

# Build rule for target.
googletest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 googletest
.PHONY : googletest

# fast build rule for target.
googletest/fast:
	$(MAKE) -f CMakeFiles/googletest.dir/build.make CMakeFiles/googletest.dir/build
.PHONY : googletest/fast

#=============================================================================
# Target rules for targets named pairing_unittest

# Build rule for target.
pairing_unittest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pairing_unittest
.PHONY : pairing_unittest

# fast build rule for target.
pairing_unittest/fast:
	$(MAKE) -f CMakeFiles/pairing_unittest.dir/build.make CMakeFiles/pairing_unittest.dir/build
.PHONY : pairing_unittest/fast

#=============================================================================
# Target rules for targets named python

# Build rule for target.
python: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 python
.PHONY : python

# fast build rule for target.
python/fast:
	$(MAKE) -f CMakeFiles/python.dir/build.make CMakeFiles/python.dir/build
.PHONY : python/fast

#=============================================================================
# Target rules for targets named test_client

# Build rule for target.
test_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_client
.PHONY : test_client

# fast build rule for target.
test_client/fast:
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/build
.PHONY : test_client/fast

#=============================================================================
# Target rules for targets named test_dh

# Build rule for target.
test_dh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_dh
.PHONY : test_dh

# fast build rule for target.
test_dh/fast:
	$(MAKE) -f CMakeFiles/test_dh.dir/build.make CMakeFiles/test_dh.dir/build
.PHONY : test_dh/fast

#=============================================================================
# Target rules for targets named test_enc

# Build rule for target.
test_enc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_enc
.PHONY : test_enc

# fast build rule for target.
test_enc/fast:
	$(MAKE) -f CMakeFiles/test_enc.dir/build.make CMakeFiles/test_enc.dir/build
.PHONY : test_enc/fast

#=============================================================================
# Target rules for targets named test_epoch

# Build rule for target.
test_epoch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_epoch
.PHONY : test_epoch

# fast build rule for target.
test_epoch/fast:
	$(MAKE) -f CMakeFiles/test_epoch.dir/build.make CMakeFiles/test_epoch.dir/build
.PHONY : test_epoch/fast

#=============================================================================
# Target rules for targets named test_hashes

# Build rule for target.
test_hashes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hashes
.PHONY : test_hashes

# fast build rule for target.
test_hashes/fast:
	$(MAKE) -f CMakeFiles/test_hashes.dir/build.make CMakeFiles/test_hashes.dir/build
.PHONY : test_hashes/fast

#=============================================================================
# Target rules for targets named test_integrate

# Build rule for target.
test_integrate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_integrate
.PHONY : test_integrate

# fast build rule for target.
test_integrate/fast:
	$(MAKE) -f CMakeFiles/test_integrate.dir/build.make CMakeFiles/test_integrate.dir/build
.PHONY : test_integrate/fast

#=============================================================================
# Target rules for targets named test_lscd

# Build rule for target.
test_lscd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_lscd
.PHONY : test_lscd

# fast build rule for target.
test_lscd/fast:
	$(MAKE) -f CMakeFiles/test_lscd.dir/build.make CMakeFiles/test_lscd.dir/build
.PHONY : test_lscd/fast

#=============================================================================
# Target rules for targets named test_pirglue

# Build rule for target.
test_pirglue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_pirglue
.PHONY : test_pirglue

# fast build rule for target.
test_pirglue/fast:
	$(MAKE) -f CMakeFiles/test_pirglue.dir/build.make CMakeFiles/test_pirglue.dir/build
.PHONY : test_pirglue/fast

#=============================================================================
# Target rules for targets named test_pirgluemt

# Build rule for target.
test_pirgluemt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_pirgluemt
.PHONY : test_pirgluemt

# fast build rule for target.
test_pirgluemt/fast:
	$(MAKE) -f CMakeFiles/test_pirgluemt.dir/build.make CMakeFiles/test_pirgluemt.dir/build
.PHONY : test_pirgluemt/fast

#=============================================================================
# Target rules for targets named test_prf

# Build rule for target.
test_prf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_prf
.PHONY : test_prf

# fast build rule for target.
test_prf/fast:
	$(MAKE) -f CMakeFiles/test_prf.dir/build.make CMakeFiles/test_prf.dir/build
.PHONY : test_prf/fast

#=============================================================================
# Target rules for targets named test_reqcd

# Build rule for target.
test_reqcd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_reqcd
.PHONY : test_reqcd

# fast build rule for target.
test_reqcd/fast:
	$(MAKE) -f CMakeFiles/test_reqcd.dir/build.make CMakeFiles/test_reqcd.dir/build
.PHONY : test_reqcd/fast

#=============================================================================
# Target rules for targets named test_rsconst

# Build rule for target.
test_rsconst: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_rsconst
.PHONY : test_rsconst

# fast build rule for target.
test_rsconst/fast:
	$(MAKE) -f CMakeFiles/test_rsconst.dir/build.make CMakeFiles/test_rsconst.dir/build
.PHONY : test_rsconst/fast

#=============================================================================
# Target rules for targets named test_rsreg

# Build rule for target.
test_rsreg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_rsreg
.PHONY : test_rsreg

# fast build rule for target.
test_rsreg/fast:
	$(MAKE) -f CMakeFiles/test_rsreg.dir/build.make CMakeFiles/test_rsreg.dir/build
.PHONY : test_rsreg/fast

#=============================================================================
# Target rules for targets named relicwrapper

# Build rule for target.
relicwrapper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 relicwrapper
.PHONY : relicwrapper

# fast build rule for target.
relicwrapper/fast:
	$(MAKE) -f relicwrapper/CMakeFiles/relicwrapper.dir/build.make relicwrapper/CMakeFiles/relicwrapper.dir/build
.PHONY : relicwrapper/fast

bytearray_unittest.o: bytearray_unittest.cpp.o
.PHONY : bytearray_unittest.o

# target to build an object file
bytearray_unittest.cpp.o:
	$(MAKE) -f CMakeFiles/bytearray_unittest.dir/build.make CMakeFiles/bytearray_unittest.dir/bytearray_unittest.cpp.o
.PHONY : bytearray_unittest.cpp.o

bytearray_unittest.i: bytearray_unittest.cpp.i
.PHONY : bytearray_unittest.i

# target to preprocess a source file
bytearray_unittest.cpp.i:
	$(MAKE) -f CMakeFiles/bytearray_unittest.dir/build.make CMakeFiles/bytearray_unittest.dir/bytearray_unittest.cpp.i
.PHONY : bytearray_unittest.cpp.i

bytearray_unittest.s: bytearray_unittest.cpp.s
.PHONY : bytearray_unittest.s

# target to generate assembly for a file
bytearray_unittest.cpp.s:
	$(MAKE) -f CMakeFiles/bytearray_unittest.dir/build.make CMakeFiles/bytearray_unittest.dir/bytearray_unittest.cpp.s
.PHONY : bytearray_unittest.cpp.s

curve25519-donna.o: curve25519-donna.c.o
.PHONY : curve25519-donna.o

# target to build an object file
curve25519-donna.c.o:
	$(MAKE) -f CMakeFiles/curve25519-donna.dir/build.make CMakeFiles/curve25519-donna.dir/curve25519-donna.c.o
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/curve25519-donna.c.o
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/curve25519-donna.c.o
.PHONY : curve25519-donna.c.o

curve25519-donna.i: curve25519-donna.c.i
.PHONY : curve25519-donna.i

# target to preprocess a source file
curve25519-donna.c.i:
	$(MAKE) -f CMakeFiles/curve25519-donna.dir/build.make CMakeFiles/curve25519-donna.dir/curve25519-donna.c.i
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/curve25519-donna.c.i
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/curve25519-donna.c.i
.PHONY : curve25519-donna.c.i

curve25519-donna.s: curve25519-donna.c.s
.PHONY : curve25519-donna.s

# target to generate assembly for a file
curve25519-donna.c.s:
	$(MAKE) -f CMakeFiles/curve25519-donna.dir/build.make CMakeFiles/curve25519-donna.dir/curve25519-donna.c.s
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/curve25519-donna.c.s
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/curve25519-donna.c.s
.PHONY : curve25519-donna.c.s

dp5clib.o: dp5clib.cpp.o
.PHONY : dp5clib.o

# target to build an object file
dp5clib.cpp.o:
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5clib.cpp.o
.PHONY : dp5clib.cpp.o

dp5clib.i: dp5clib.cpp.i
.PHONY : dp5clib.i

# target to preprocess a source file
dp5clib.cpp.i:
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5clib.cpp.i
.PHONY : dp5clib.cpp.i

dp5clib.s: dp5clib.cpp.s
.PHONY : dp5clib.s

# target to generate assembly for a file
dp5clib.cpp.s:
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5clib.cpp.s
.PHONY : dp5clib.cpp.s

dp5combregclient.o: dp5combregclient.cpp.o
.PHONY : dp5combregclient.o

# target to build an object file
dp5combregclient.cpp.o:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5combregclient.cpp.o
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5combregclient.cpp.o
	$(MAKE) -f CMakeFiles/dp5combregclient_unittest.dir/build.make CMakeFiles/dp5combregclient_unittest.dir/dp5combregclient.cpp.o
.PHONY : dp5combregclient.cpp.o

dp5combregclient.i: dp5combregclient.cpp.i
.PHONY : dp5combregclient.i

# target to preprocess a source file
dp5combregclient.cpp.i:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5combregclient.cpp.i
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5combregclient.cpp.i
	$(MAKE) -f CMakeFiles/dp5combregclient_unittest.dir/build.make CMakeFiles/dp5combregclient_unittest.dir/dp5combregclient.cpp.i
.PHONY : dp5combregclient.cpp.i

dp5combregclient.s: dp5combregclient.cpp.s
.PHONY : dp5combregclient.s

# target to generate assembly for a file
dp5combregclient.cpp.s:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5combregclient.cpp.s
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5combregclient.cpp.s
	$(MAKE) -f CMakeFiles/dp5combregclient_unittest.dir/build.make CMakeFiles/dp5combregclient_unittest.dir/dp5combregclient.cpp.s
.PHONY : dp5combregclient.cpp.s

dp5combregclient_unittest.o: dp5combregclient_unittest.cpp.o
.PHONY : dp5combregclient_unittest.o

# target to build an object file
dp5combregclient_unittest.cpp.o:
	$(MAKE) -f CMakeFiles/dp5combregclient_unittest.dir/build.make CMakeFiles/dp5combregclient_unittest.dir/dp5combregclient_unittest.cpp.o
.PHONY : dp5combregclient_unittest.cpp.o

dp5combregclient_unittest.i: dp5combregclient_unittest.cpp.i
.PHONY : dp5combregclient_unittest.i

# target to preprocess a source file
dp5combregclient_unittest.cpp.i:
	$(MAKE) -f CMakeFiles/dp5combregclient_unittest.dir/build.make CMakeFiles/dp5combregclient_unittest.dir/dp5combregclient_unittest.cpp.i
.PHONY : dp5combregclient_unittest.cpp.i

dp5combregclient_unittest.s: dp5combregclient_unittest.cpp.s
.PHONY : dp5combregclient_unittest.s

# target to generate assembly for a file
dp5combregclient_unittest.cpp.s:
	$(MAKE) -f CMakeFiles/dp5combregclient_unittest.dir/build.make CMakeFiles/dp5combregclient_unittest.dir/dp5combregclient_unittest.cpp.s
.PHONY : dp5combregclient_unittest.cpp.s

dp5integrationtest.o: dp5integrationtest.cpp.o
.PHONY : dp5integrationtest.o

# target to build an object file
dp5integrationtest.cpp.o:
	$(MAKE) -f CMakeFiles/test_integrate.dir/build.make CMakeFiles/test_integrate.dir/dp5integrationtest.cpp.o
.PHONY : dp5integrationtest.cpp.o

dp5integrationtest.i: dp5integrationtest.cpp.i
.PHONY : dp5integrationtest.i

# target to preprocess a source file
dp5integrationtest.cpp.i:
	$(MAKE) -f CMakeFiles/test_integrate.dir/build.make CMakeFiles/test_integrate.dir/dp5integrationtest.cpp.i
.PHONY : dp5integrationtest.cpp.i

dp5integrationtest.s: dp5integrationtest.cpp.s
.PHONY : dp5integrationtest.s

# target to generate assembly for a file
dp5integrationtest.cpp.s:
	$(MAKE) -f CMakeFiles/test_integrate.dir/build.make CMakeFiles/test_integrate.dir/dp5integrationtest.cpp.s
.PHONY : dp5integrationtest.cpp.s

dp5lookupclient.o: dp5lookupclient.cpp.o
.PHONY : dp5lookupclient.o

# target to build an object file
dp5lookupclient.cpp.o:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5lookupclient.cpp.o
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5lookupclient.cpp.o
	$(MAKE) -f CMakeFiles/dp5lookupclient_unittest.dir/build.make CMakeFiles/dp5lookupclient_unittest.dir/dp5lookupclient.cpp.o
	$(MAKE) -f CMakeFiles/test_pirglue.dir/build.make CMakeFiles/test_pirglue.dir/dp5lookupclient.cpp.o
	$(MAKE) -f CMakeFiles/test_pirgluemt.dir/build.make CMakeFiles/test_pirgluemt.dir/dp5lookupclient.cpp.o
	$(MAKE) -f CMakeFiles/test_reqcd.dir/build.make CMakeFiles/test_reqcd.dir/dp5lookupclient.cpp.o
.PHONY : dp5lookupclient.cpp.o

dp5lookupclient.i: dp5lookupclient.cpp.i
.PHONY : dp5lookupclient.i

# target to preprocess a source file
dp5lookupclient.cpp.i:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5lookupclient.cpp.i
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5lookupclient.cpp.i
	$(MAKE) -f CMakeFiles/dp5lookupclient_unittest.dir/build.make CMakeFiles/dp5lookupclient_unittest.dir/dp5lookupclient.cpp.i
	$(MAKE) -f CMakeFiles/test_pirglue.dir/build.make CMakeFiles/test_pirglue.dir/dp5lookupclient.cpp.i
	$(MAKE) -f CMakeFiles/test_pirgluemt.dir/build.make CMakeFiles/test_pirgluemt.dir/dp5lookupclient.cpp.i
	$(MAKE) -f CMakeFiles/test_reqcd.dir/build.make CMakeFiles/test_reqcd.dir/dp5lookupclient.cpp.i
.PHONY : dp5lookupclient.cpp.i

dp5lookupclient.s: dp5lookupclient.cpp.s
.PHONY : dp5lookupclient.s

# target to generate assembly for a file
dp5lookupclient.cpp.s:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5lookupclient.cpp.s
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5lookupclient.cpp.s
	$(MAKE) -f CMakeFiles/dp5lookupclient_unittest.dir/build.make CMakeFiles/dp5lookupclient_unittest.dir/dp5lookupclient.cpp.s
	$(MAKE) -f CMakeFiles/test_pirglue.dir/build.make CMakeFiles/test_pirglue.dir/dp5lookupclient.cpp.s
	$(MAKE) -f CMakeFiles/test_pirgluemt.dir/build.make CMakeFiles/test_pirgluemt.dir/dp5lookupclient.cpp.s
	$(MAKE) -f CMakeFiles/test_reqcd.dir/build.make CMakeFiles/test_reqcd.dir/dp5lookupclient.cpp.s
.PHONY : dp5lookupclient.cpp.s

dp5lookupclient_unittest.o: dp5lookupclient_unittest.cpp.o
.PHONY : dp5lookupclient_unittest.o

# target to build an object file
dp5lookupclient_unittest.cpp.o:
	$(MAKE) -f CMakeFiles/dp5lookupclient_unittest.dir/build.make CMakeFiles/dp5lookupclient_unittest.dir/dp5lookupclient_unittest.cpp.o
.PHONY : dp5lookupclient_unittest.cpp.o

dp5lookupclient_unittest.i: dp5lookupclient_unittest.cpp.i
.PHONY : dp5lookupclient_unittest.i

# target to preprocess a source file
dp5lookupclient_unittest.cpp.i:
	$(MAKE) -f CMakeFiles/dp5lookupclient_unittest.dir/build.make CMakeFiles/dp5lookupclient_unittest.dir/dp5lookupclient_unittest.cpp.i
.PHONY : dp5lookupclient_unittest.cpp.i

dp5lookupclient_unittest.s: dp5lookupclient_unittest.cpp.s
.PHONY : dp5lookupclient_unittest.s

# target to generate assembly for a file
dp5lookupclient_unittest.cpp.s:
	$(MAKE) -f CMakeFiles/dp5lookupclient_unittest.dir/build.make CMakeFiles/dp5lookupclient_unittest.dir/dp5lookupclient_unittest.cpp.s
.PHONY : dp5lookupclient_unittest.cpp.s

dp5lookupserver.o: dp5lookupserver.cpp.o
.PHONY : dp5lookupserver.o

# target to build an object file
dp5lookupserver.cpp.o:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5lookupserver.cpp.o
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5lookupserver.cpp.o
	$(MAKE) -f CMakeFiles/test_lscd.dir/build.make CMakeFiles/test_lscd.dir/dp5lookupserver.cpp.o
	$(MAKE) -f CMakeFiles/test_pirglue.dir/build.make CMakeFiles/test_pirglue.dir/dp5lookupserver.cpp.o
	$(MAKE) -f CMakeFiles/test_pirgluemt.dir/build.make CMakeFiles/test_pirgluemt.dir/dp5lookupserver.cpp.o
.PHONY : dp5lookupserver.cpp.o

dp5lookupserver.i: dp5lookupserver.cpp.i
.PHONY : dp5lookupserver.i

# target to preprocess a source file
dp5lookupserver.cpp.i:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5lookupserver.cpp.i
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5lookupserver.cpp.i
	$(MAKE) -f CMakeFiles/test_lscd.dir/build.make CMakeFiles/test_lscd.dir/dp5lookupserver.cpp.i
	$(MAKE) -f CMakeFiles/test_pirglue.dir/build.make CMakeFiles/test_pirglue.dir/dp5lookupserver.cpp.i
	$(MAKE) -f CMakeFiles/test_pirgluemt.dir/build.make CMakeFiles/test_pirgluemt.dir/dp5lookupserver.cpp.i
.PHONY : dp5lookupserver.cpp.i

dp5lookupserver.s: dp5lookupserver.cpp.s
.PHONY : dp5lookupserver.s

# target to generate assembly for a file
dp5lookupserver.cpp.s:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5lookupserver.cpp.s
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5lookupserver.cpp.s
	$(MAKE) -f CMakeFiles/test_lscd.dir/build.make CMakeFiles/test_lscd.dir/dp5lookupserver.cpp.s
	$(MAKE) -f CMakeFiles/test_pirglue.dir/build.make CMakeFiles/test_pirglue.dir/dp5lookupserver.cpp.s
	$(MAKE) -f CMakeFiles/test_pirgluemt.dir/build.make CMakeFiles/test_pirgluemt.dir/dp5lookupserver.cpp.s
.PHONY : dp5lookupserver.cpp.s

dp5metadata.o: dp5metadata.cpp.o
.PHONY : dp5metadata.o

# target to build an object file
dp5metadata.cpp.o:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5metadata.cpp.o
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5metadata.cpp.o
	$(MAKE) -f CMakeFiles/dp5lookupclient_unittest.dir/build.make CMakeFiles/dp5lookupclient_unittest.dir/dp5metadata.cpp.o
	$(MAKE) -f CMakeFiles/dp5metadata_unittest.dir/build.make CMakeFiles/dp5metadata_unittest.dir/dp5metadata.cpp.o
	$(MAKE) -f CMakeFiles/test_lscd.dir/build.make CMakeFiles/test_lscd.dir/dp5metadata.cpp.o
	$(MAKE) -f CMakeFiles/test_pirglue.dir/build.make CMakeFiles/test_pirglue.dir/dp5metadata.cpp.o
	$(MAKE) -f CMakeFiles/test_pirgluemt.dir/build.make CMakeFiles/test_pirgluemt.dir/dp5metadata.cpp.o
	$(MAKE) -f CMakeFiles/test_reqcd.dir/build.make CMakeFiles/test_reqcd.dir/dp5metadata.cpp.o
	$(MAKE) -f CMakeFiles/test_rsconst.dir/build.make CMakeFiles/test_rsconst.dir/dp5metadata.cpp.o
	$(MAKE) -f CMakeFiles/test_rsreg.dir/build.make CMakeFiles/test_rsreg.dir/dp5metadata.cpp.o
.PHONY : dp5metadata.cpp.o

dp5metadata.i: dp5metadata.cpp.i
.PHONY : dp5metadata.i

# target to preprocess a source file
dp5metadata.cpp.i:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5metadata.cpp.i
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5metadata.cpp.i
	$(MAKE) -f CMakeFiles/dp5lookupclient_unittest.dir/build.make CMakeFiles/dp5lookupclient_unittest.dir/dp5metadata.cpp.i
	$(MAKE) -f CMakeFiles/dp5metadata_unittest.dir/build.make CMakeFiles/dp5metadata_unittest.dir/dp5metadata.cpp.i
	$(MAKE) -f CMakeFiles/test_lscd.dir/build.make CMakeFiles/test_lscd.dir/dp5metadata.cpp.i
	$(MAKE) -f CMakeFiles/test_pirglue.dir/build.make CMakeFiles/test_pirglue.dir/dp5metadata.cpp.i
	$(MAKE) -f CMakeFiles/test_pirgluemt.dir/build.make CMakeFiles/test_pirgluemt.dir/dp5metadata.cpp.i
	$(MAKE) -f CMakeFiles/test_reqcd.dir/build.make CMakeFiles/test_reqcd.dir/dp5metadata.cpp.i
	$(MAKE) -f CMakeFiles/test_rsconst.dir/build.make CMakeFiles/test_rsconst.dir/dp5metadata.cpp.i
	$(MAKE) -f CMakeFiles/test_rsreg.dir/build.make CMakeFiles/test_rsreg.dir/dp5metadata.cpp.i
.PHONY : dp5metadata.cpp.i

dp5metadata.s: dp5metadata.cpp.s
.PHONY : dp5metadata.s

# target to generate assembly for a file
dp5metadata.cpp.s:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5metadata.cpp.s
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5metadata.cpp.s
	$(MAKE) -f CMakeFiles/dp5lookupclient_unittest.dir/build.make CMakeFiles/dp5lookupclient_unittest.dir/dp5metadata.cpp.s
	$(MAKE) -f CMakeFiles/dp5metadata_unittest.dir/build.make CMakeFiles/dp5metadata_unittest.dir/dp5metadata.cpp.s
	$(MAKE) -f CMakeFiles/test_lscd.dir/build.make CMakeFiles/test_lscd.dir/dp5metadata.cpp.s
	$(MAKE) -f CMakeFiles/test_pirglue.dir/build.make CMakeFiles/test_pirglue.dir/dp5metadata.cpp.s
	$(MAKE) -f CMakeFiles/test_pirgluemt.dir/build.make CMakeFiles/test_pirgluemt.dir/dp5metadata.cpp.s
	$(MAKE) -f CMakeFiles/test_reqcd.dir/build.make CMakeFiles/test_reqcd.dir/dp5metadata.cpp.s
	$(MAKE) -f CMakeFiles/test_rsconst.dir/build.make CMakeFiles/test_rsconst.dir/dp5metadata.cpp.s
	$(MAKE) -f CMakeFiles/test_rsreg.dir/build.make CMakeFiles/test_rsreg.dir/dp5metadata.cpp.s
.PHONY : dp5metadata.cpp.s

dp5metadata_unittest.o: dp5metadata_unittest.cpp.o
.PHONY : dp5metadata_unittest.o

# target to build an object file
dp5metadata_unittest.cpp.o:
	$(MAKE) -f CMakeFiles/dp5metadata_unittest.dir/build.make CMakeFiles/dp5metadata_unittest.dir/dp5metadata_unittest.cpp.o
.PHONY : dp5metadata_unittest.cpp.o

dp5metadata_unittest.i: dp5metadata_unittest.cpp.i
.PHONY : dp5metadata_unittest.i

# target to preprocess a source file
dp5metadata_unittest.cpp.i:
	$(MAKE) -f CMakeFiles/dp5metadata_unittest.dir/build.make CMakeFiles/dp5metadata_unittest.dir/dp5metadata_unittest.cpp.i
.PHONY : dp5metadata_unittest.cpp.i

dp5metadata_unittest.s: dp5metadata_unittest.cpp.s
.PHONY : dp5metadata_unittest.s

# target to generate assembly for a file
dp5metadata_unittest.cpp.s:
	$(MAKE) -f CMakeFiles/dp5metadata_unittest.dir/build.make CMakeFiles/dp5metadata_unittest.dir/dp5metadata_unittest.cpp.s
.PHONY : dp5metadata_unittest.cpp.s

dp5params.o: dp5params.cpp.o
.PHONY : dp5params.o

# target to build an object file
dp5params.cpp.o:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/dp5combregclient_unittest.dir/build.make CMakeFiles/dp5combregclient_unittest.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/dp5lookupclient_unittest.dir/build.make CMakeFiles/dp5lookupclient_unittest.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/dp5metadata_unittest.dir/build.make CMakeFiles/dp5metadata_unittest.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/enc_test.dir/build.make CMakeFiles/enc_test.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/pairing_unittest.dir/build.make CMakeFiles/pairing_unittest.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/test_dh.dir/build.make CMakeFiles/test_dh.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/test_enc.dir/build.make CMakeFiles/test_enc.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/test_epoch.dir/build.make CMakeFiles/test_epoch.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/test_hashes.dir/build.make CMakeFiles/test_hashes.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/test_lscd.dir/build.make CMakeFiles/test_lscd.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/test_pirglue.dir/build.make CMakeFiles/test_pirglue.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/test_pirgluemt.dir/build.make CMakeFiles/test_pirgluemt.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/test_prf.dir/build.make CMakeFiles/test_prf.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/test_reqcd.dir/build.make CMakeFiles/test_reqcd.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/test_rsconst.dir/build.make CMakeFiles/test_rsconst.dir/dp5params.cpp.o
	$(MAKE) -f CMakeFiles/test_rsreg.dir/build.make CMakeFiles/test_rsreg.dir/dp5params.cpp.o
.PHONY : dp5params.cpp.o

dp5params.i: dp5params.cpp.i
.PHONY : dp5params.i

# target to preprocess a source file
dp5params.cpp.i:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/dp5combregclient_unittest.dir/build.make CMakeFiles/dp5combregclient_unittest.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/dp5lookupclient_unittest.dir/build.make CMakeFiles/dp5lookupclient_unittest.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/dp5metadata_unittest.dir/build.make CMakeFiles/dp5metadata_unittest.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/enc_test.dir/build.make CMakeFiles/enc_test.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/pairing_unittest.dir/build.make CMakeFiles/pairing_unittest.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/test_dh.dir/build.make CMakeFiles/test_dh.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/test_enc.dir/build.make CMakeFiles/test_enc.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/test_epoch.dir/build.make CMakeFiles/test_epoch.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/test_hashes.dir/build.make CMakeFiles/test_hashes.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/test_lscd.dir/build.make CMakeFiles/test_lscd.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/test_pirglue.dir/build.make CMakeFiles/test_pirglue.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/test_pirgluemt.dir/build.make CMakeFiles/test_pirgluemt.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/test_prf.dir/build.make CMakeFiles/test_prf.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/test_reqcd.dir/build.make CMakeFiles/test_reqcd.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/test_rsconst.dir/build.make CMakeFiles/test_rsconst.dir/dp5params.cpp.i
	$(MAKE) -f CMakeFiles/test_rsreg.dir/build.make CMakeFiles/test_rsreg.dir/dp5params.cpp.i
.PHONY : dp5params.cpp.i

dp5params.s: dp5params.cpp.s
.PHONY : dp5params.s

# target to generate assembly for a file
dp5params.cpp.s:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/dp5combregclient_unittest.dir/build.make CMakeFiles/dp5combregclient_unittest.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/dp5lookupclient_unittest.dir/build.make CMakeFiles/dp5lookupclient_unittest.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/dp5metadata_unittest.dir/build.make CMakeFiles/dp5metadata_unittest.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/enc_test.dir/build.make CMakeFiles/enc_test.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/pairing_unittest.dir/build.make CMakeFiles/pairing_unittest.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/test_dh.dir/build.make CMakeFiles/test_dh.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/test_enc.dir/build.make CMakeFiles/test_enc.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/test_epoch.dir/build.make CMakeFiles/test_epoch.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/test_hashes.dir/build.make CMakeFiles/test_hashes.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/test_lscd.dir/build.make CMakeFiles/test_lscd.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/test_pirglue.dir/build.make CMakeFiles/test_pirglue.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/test_pirgluemt.dir/build.make CMakeFiles/test_pirgluemt.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/test_prf.dir/build.make CMakeFiles/test_prf.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/test_reqcd.dir/build.make CMakeFiles/test_reqcd.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/test_rsconst.dir/build.make CMakeFiles/test_rsconst.dir/dp5params.cpp.s
	$(MAKE) -f CMakeFiles/test_rsreg.dir/build.make CMakeFiles/test_rsreg.dir/dp5params.cpp.s
.PHONY : dp5params.cpp.s

dp5regclient.o: dp5regclient.cpp.o
.PHONY : dp5regclient.o

# target to build an object file
dp5regclient.cpp.o:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5regclient.cpp.o
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5regclient.cpp.o
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/dp5regclient.cpp.o
.PHONY : dp5regclient.cpp.o

dp5regclient.i: dp5regclient.cpp.i
.PHONY : dp5regclient.i

# target to preprocess a source file
dp5regclient.cpp.i:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5regclient.cpp.i
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5regclient.cpp.i
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/dp5regclient.cpp.i
.PHONY : dp5regclient.cpp.i

dp5regclient.s: dp5regclient.cpp.s
.PHONY : dp5regclient.s

# target to generate assembly for a file
dp5regclient.cpp.s:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5regclient.cpp.s
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5regclient.cpp.s
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/dp5regclient.cpp.s
.PHONY : dp5regclient.cpp.s

dp5regserver.o: dp5regserver.cpp.o
.PHONY : dp5regserver.o

# target to build an object file
dp5regserver.cpp.o:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5regserver.cpp.o
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5regserver.cpp.o
	$(MAKE) -f CMakeFiles/test_rsconst.dir/build.make CMakeFiles/test_rsconst.dir/dp5regserver.cpp.o
	$(MAKE) -f CMakeFiles/test_rsreg.dir/build.make CMakeFiles/test_rsreg.dir/dp5regserver.cpp.o
.PHONY : dp5regserver.cpp.o

dp5regserver.i: dp5regserver.cpp.i
.PHONY : dp5regserver.i

# target to preprocess a source file
dp5regserver.cpp.i:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5regserver.cpp.i
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5regserver.cpp.i
	$(MAKE) -f CMakeFiles/test_rsconst.dir/build.make CMakeFiles/test_rsconst.dir/dp5regserver.cpp.i
	$(MAKE) -f CMakeFiles/test_rsreg.dir/build.make CMakeFiles/test_rsreg.dir/dp5regserver.cpp.i
.PHONY : dp5regserver.cpp.i

dp5regserver.s: dp5regserver.cpp.s
.PHONY : dp5regserver.s

# target to generate assembly for a file
dp5regserver.cpp.s:
	$(MAKE) -f CMakeFiles/dp5.dir/build.make CMakeFiles/dp5.dir/dp5regserver.cpp.s
	$(MAKE) -f CMakeFiles/dp5clib.dir/build.make CMakeFiles/dp5clib.dir/dp5regserver.cpp.s
	$(MAKE) -f CMakeFiles/test_rsconst.dir/build.make CMakeFiles/test_rsconst.dir/dp5regserver.cpp.s
	$(MAKE) -f CMakeFiles/test_rsreg.dir/build.make CMakeFiles/test_rsreg.dir/dp5regserver.cpp.s
.PHONY : dp5regserver.cpp.s

enc_test.o: enc_test.cpp.o
.PHONY : enc_test.o

# target to build an object file
enc_test.cpp.o:
	$(MAKE) -f CMakeFiles/enc_test.dir/build.make CMakeFiles/enc_test.dir/enc_test.cpp.o
.PHONY : enc_test.cpp.o

enc_test.i: enc_test.cpp.i
.PHONY : enc_test.i

# target to preprocess a source file
enc_test.cpp.i:
	$(MAKE) -f CMakeFiles/enc_test.dir/build.make CMakeFiles/enc_test.dir/enc_test.cpp.i
.PHONY : enc_test.cpp.i

enc_test.s: enc_test.cpp.s
.PHONY : enc_test.s

# target to generate assembly for a file
enc_test.cpp.s:
	$(MAKE) -f CMakeFiles/enc_test.dir/build.make CMakeFiles/enc_test.dir/enc_test.cpp.s
.PHONY : enc_test.cpp.s

pairing_unittest.o: pairing_unittest.cpp.o
.PHONY : pairing_unittest.o

# target to build an object file
pairing_unittest.cpp.o:
	$(MAKE) -f CMakeFiles/pairing_unittest.dir/build.make CMakeFiles/pairing_unittest.dir/pairing_unittest.cpp.o
.PHONY : pairing_unittest.cpp.o

pairing_unittest.i: pairing_unittest.cpp.i
.PHONY : pairing_unittest.i

# target to preprocess a source file
pairing_unittest.cpp.i:
	$(MAKE) -f CMakeFiles/pairing_unittest.dir/build.make CMakeFiles/pairing_unittest.dir/pairing_unittest.cpp.i
.PHONY : pairing_unittest.cpp.i

pairing_unittest.s: pairing_unittest.cpp.s
.PHONY : pairing_unittest.s

# target to generate assembly for a file
pairing_unittest.cpp.s:
	$(MAKE) -f CMakeFiles/pairing_unittest.dir/build.make CMakeFiles/pairing_unittest.dir/pairing_unittest.cpp.s
.PHONY : pairing_unittest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Percy++"
	@echo "... Relic"
	@echo "... bytearray_unittest"
	@echo "... curve25519-donna"
	@echo "... dp5"
	@echo "... dp5clib"
	@echo "... dp5combregclient_unittest"
	@echo "... dp5lookupclient_unittest"
	@echo "... dp5metadata_unittest"
	@echo "... edit_cache"
	@echo "... enc_test"
	@echo "... googletest"
	@echo "... pairing_unittest"
	@echo "... python"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... test_client"
	@echo "... test_dh"
	@echo "... test_enc"
	@echo "... test_epoch"
	@echo "... test_hashes"
	@echo "... test_integrate"
	@echo "... test_lscd"
	@echo "... test_pirglue"
	@echo "... test_pirgluemt"
	@echo "... test_prf"
	@echo "... test_reqcd"
	@echo "... test_rsconst"
	@echo "... test_rsreg"
	@echo "... relicwrapper"
	@echo "... bytearray_unittest.o"
	@echo "... bytearray_unittest.i"
	@echo "... bytearray_unittest.s"
	@echo "... curve25519-donna.o"
	@echo "... curve25519-donna.i"
	@echo "... curve25519-donna.s"
	@echo "... dp5clib.o"
	@echo "... dp5clib.i"
	@echo "... dp5clib.s"
	@echo "... dp5combregclient.o"
	@echo "... dp5combregclient.i"
	@echo "... dp5combregclient.s"
	@echo "... dp5combregclient_unittest.o"
	@echo "... dp5combregclient_unittest.i"
	@echo "... dp5combregclient_unittest.s"
	@echo "... dp5integrationtest.o"
	@echo "... dp5integrationtest.i"
	@echo "... dp5integrationtest.s"
	@echo "... dp5lookupclient.o"
	@echo "... dp5lookupclient.i"
	@echo "... dp5lookupclient.s"
	@echo "... dp5lookupclient_unittest.o"
	@echo "... dp5lookupclient_unittest.i"
	@echo "... dp5lookupclient_unittest.s"
	@echo "... dp5lookupserver.o"
	@echo "... dp5lookupserver.i"
	@echo "... dp5lookupserver.s"
	@echo "... dp5metadata.o"
	@echo "... dp5metadata.i"
	@echo "... dp5metadata.s"
	@echo "... dp5metadata_unittest.o"
	@echo "... dp5metadata_unittest.i"
	@echo "... dp5metadata_unittest.s"
	@echo "... dp5params.o"
	@echo "... dp5params.i"
	@echo "... dp5params.s"
	@echo "... dp5regclient.o"
	@echo "... dp5regclient.i"
	@echo "... dp5regclient.s"
	@echo "... dp5regserver.o"
	@echo "... dp5regserver.i"
	@echo "... dp5regserver.s"
	@echo "... enc_test.o"
	@echo "... enc_test.i"
	@echo "... enc_test.s"
	@echo "... pairing_unittest.o"
	@echo "... pairing_unittest.i"
	@echo "... pairing_unittest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

